---
# tasks file for aws_provision
- ec2:
        region: ap-south-1
        image: ami-0bcf5425cdc1d8a85
        instance_type: t2.micro
        vpc_subnet_id: subnet-c8c5cca0
        group_id: sg-026dd3773ee684723
        key_name: aws_putty
        aws_access_key: {{ access_key }}
        aws_secret_key: {{ secret_key }}
        assign_public_ip: yes
        wait: yes
  register: x1
- blockinfile:
        path: "/root/ip.txt"
        marker: ""
        block: |
                   [master]
                   {{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/aws_putty.pem ansible_connection=ssh
  loop: "{{ x1.instances }}"
- ec2:
        region: ap-south-1
        image: ami-0bcf5425cdc1d8a85
        instance_type: t2.micro
        vpc_subnet_id: subnet-c8c5cca0
        group_id: sg-026dd3773ee684723
        key_name: aws_putty
        aws_access_key: {{ access_key }}
        aws_secret_key: {{ secret_key }}
        assign_public_ip: yes
        wait: yes
        count: "{{ count_slaves }}" 
  register: x2

- blockinfile:
        path: "/root/ip.txt"
        marker: ""
        block: |
                   [slaves]
                   {{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/root/aws_putty.pem ansible_connection=ssh
  loop: "{{ x2.instances }}"

